name: customer_app
description: MercaColombia.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  nb_utils: ^4.6.20
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  cached_network_image: ^3.2.1
  badges: ^2.0.2
  rxdart:
  intl:
  dio: ^4.0.4
  skeleton_text: ^3.0.0
  photo_view: 
  animated_splash_screen: ^1.2.0
  form_field_validator: ^1.1.0
  encrypt: ^5.0.1
  provider: ^6.0.2
  google_fonts: ^3.0.1

  flutter_localizations: # Add this line
      sdk: flutter         # Add this line
  dropdown_search: ^5.0.2
  flutter_datetime_picker: ^1.5.1
  rounded_loading_button: ^2.1.0
  url_launcher: ^6.1.5
  connectivity_plus: ^2.3.6
  get: ^4.6.5
  image_picker: ^0.8.5+3
  font_awesome_flutter: ^10.1.0
  package_info: ^2.0.2
  custom_clippers: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: 'assets/icons/launcher_icon.png'

flutter:

  uses-material-design: true
  
  assets:
    - assets/icons/
    - assets/images/
    - assets/images/icons/
    - assets/images/splash_screen/
    - assets/images/category/
    - assets/images/backgrounds/

  fonts:
    - family: Verdana     
      fonts:
        - asset: assets/fonts/Verdana.ttf
    - family: Times     
      fonts:
        - asset: assets/fonts/times_new_roman_bold_italic.ttf
        - asset: assets/fonts/times_new_roman_bold.ttf
        - asset: assets/fonts/times_new_roman_italic.ttf
        - asset: assets/fonts/times_new_roman.ttf



